spring:
  application:
    name: ${APPLICATION_NAME:stock-sim-app}
  # datasource:
    # platform: postgres
    # url: jdbc:postgresql://localhost:5432/postgres
    # username: postgres
    # password: postgres
    # driverClassName: org.postgresql.Driver
  # jpa:
  #   database: POSTGRESQL
  #   show-sql: true
  #   generate-ddl: true
  #   hibernate:
  #     ddl-auto: create

server:
  servlet:
    context-path: /stocksim
  port: 8084

logging:
  level:
    com.mahesh.stock-sim-app : INFO